###################################################
# Secure Docker Compose for Todo App
#
# Production-ready setup with security hardening
###################################################

services:
  ###################################################
  # Service: backend (development - API only)
  ###################################################
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
      NODE_ENV: development
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/usr/local/app/src
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    restart: unless-stopped

  ###################################################
  # Service: mysql
  ###################################################
  mysql:
    image: mysql:9.3
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    restart: unless-stopped

  ###################################################
  # Service: client (React frontend)
  ###################################################
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - ./client/index.html:/app/index.html
      - ./client/vite.config.js:/app/vite.config.js
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    restart: unless-stopped

###################################################
# Volumes
###################################################
volumes:
  todo-mysql-data:
    driver: local
