###################################################
# Advanced Docker Compose for Todo App
#
# Production-ready with security, monitoring, and performance optimizations
###################################################

version: '3.9'

services:
  ###################################################
  # Service: backend (Node.js API)
  ###################################################
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-development}
    image: todo-app-backend:latest
    container_name: todo-backend
    hostname: backend
    environment:
      # Database configuration
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER:-todouser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secure_password_change_me}
      MYSQL_DB: ${MYSQL_DB:-todos}
      
      # Application configuration
      NODE_ENV: ${NODE_ENV:-development}
      JWT_SECRET: ${JWT_SECRET:-change-this-in-production-use-long-random-string}
      PORT: 3000
      
      # Security headers
      HELMET_ENABLED: true
      RATE_LIMIT_ENABLED: true
      RATE_LIMIT_MAX: 100
      RATE_LIMIT_WINDOW_MS: 900000
      
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-info}
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    volumes:
      - ./backend/src:/usr/local/app/src:ro
      - backend-logs:/usr/local/app/logs
    networks:
      - app-network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,nodev,size=64m
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    mem_limit: 512m
    cpus: 1.0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ###################################################
  # Service: mysql
  ###################################################
  mysql:
    image: mysql:9.3
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    restart: unless-stopped

  ###################################################
  # Service: client (React frontend)
  ###################################################
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - ./client/index.html:/app/index.html
      - ./client/vite.config.js:/app/vite.config.js
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    restart: unless-stopped

###################################################
# Volumes
###################################################
volumes:
  todo-mysql-data:
    driver: local
